### ISSUE TITLE
Intro Doesn't Start from first slide

### ISSUE THREAD

**Issue by shaulhadar** [scottopolis/wpIonic#4] opened 2015-03-21 08:37 UTC
Hi Scott, I noticed that if you go to the intro page after starting the app, it will show the last slide.... Is there any way to do that the slider will begin from the first page?  

thanks,
Shaul.

**Comment by scottopolis** [comment] 2015-03-22 17:48
The intro remembers what slide you left off, so if you went through it and then went back it would be on the last slide. You could add something to AppCtrl to reset it when going back, I'd be happy to look at a pull request for this.

**Comment by shaulhadar** [comment] 2015-03-23 06:33
Hi Scott, thanks for your help :) I think i saw something about this in the ionic forum, i will check and let you know if i can find any update for this issue.... this is a universal ionic issue, not specific for your project by the way..

**Comment by scottopolis** [comment] 2015-03-23 15:31
No problem! (This is not a bug, just a preference btw) Closing ticket.

**Closed as completed by scottopolis** 2015-03-23 15:31 UTC
